### ISSUE TITLE
Wrong Model Name

### ISSUE THREAD

**Issue by heloimnew** [horacio9a/chaturbate-anonymous#9]
I've tried re-installing/downloading and such, using a different stream program but all are giving me wrong model name error. Try for yourself, I think something changed on cb side.
![Untitled](https://user-images.githubusercontent.com/49543338/68519443-170b8100-025f-11ea-9e8b-1d375f17f5ff.png)

**Comment by aylssag6** [comment]
Im getting this too, it seems to be because chaturbate changed something with their video player.
The actual cause of error is this line

hlsurl0 = dec.split("source src='")[1]

I printed out "dec" and it no longer contains "source src="

![a2aeabacfede712cf837904f535de513](https://user-images.githubusercontent.com/50265523/68522570-a70af400-027a-11ea-8fa5-408ae3d256c3.png)
This is from a chaturbate stream, it looks to be the new video source, but im not sure how to capture it.

**Comment by horacio9a** [comment]
Really, Chaturbate has changed its video player a lot. I just finished and tested all the scripts that needed to be adapted to the new situation so that all the scripts work as they have done so far (v.1.0.9).

**Comment by heloimnew** [comment]
There seems to be an issue using the new scripts using the .bat files. It no longer displays wrong model name but when trying to record it gives me this message.
![Untitled](https://user-images.githubusercontent.com/49543338/69471522-07fff500-0d6e-11ea-993e-cdc92b680518.png)

**Comment by heloimnew** [comment]
Huh, now I'm getting this error.
![Untitled](https://user-images.githubusercontent.com/49543338/69472246-9035c880-0d75-11ea-910e-473f27403a70.png)

**Comment by horacio9a** [comment]
I have tried it now and as you can see everything is working OK. You gave too little information. Can you record another model? Maybe the problem is that the model went to a private show?
![CBA](https://user-images.githubusercontent.com/17076459/69482291-764dc180-0e19-11ea-9e4f-485c61d81e82.jpg)

**Comment by heloimnew** [comment]
I do apologize, I'm new to this. I made sure to try other streams and make sure they were online, but the script seems to be working perfectly now. Quite odd, but thank you for the quick responses nonetheless.

Edit: Running some tests and it seems for some reason streams don't work where others do. I can't seem to find the correlating factor.
